all:
	cp ../../../../svn.geostandaarden.nl/Datatypes/datatypen-ISO19107-2003.xml .
	cp ../../../../svn.geostandaarden.nl/Datatypes/datatypen-MIM.xml .
	cp ../../../../svn.geostandaarden.nl/Datatypes/datatypen-overig.xml .
